# Generated by Django 6.0 on 2026-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
