# Generated by Django 6.0 on 2026-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_seller_verified_user_role_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='pan_number',
            new_name='PAN_NUMBER',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payout_gateway',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('stripe', 'Stripe')], default='esewa', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payout_id',
            field=models.CharField(default='', help_text='eSewa ID (Phone) or Stripe Account ID', max_length=150),
            preserve_default=False,
        ),
    ]
