# Generated by Django 6.0 on 2026-07-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', max_length=512, null=True),
        ),
    ]
