# Generated by Django 6.0 on 2026-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Optional seller latitude for nearby-product matching', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Optional seller longitude for nearby-product matching', null=True),
        ),
    ]
