# Generated by Django 6.0 on 2026-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('stripe', 'Stripe')], max_length=20),
        ),
    ]
