# Generated by Django 6.0 on 2026-07-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('litre', 'Litres (L)'), ('ml', 'Millilitres (mL)'), ('piece', 'Piece / Item'), ('pack', 'Pack / Packet'), ('bag', 'Bag'), ('bottle', 'Bottle'), ('box', 'Box')], default='piece', help_text='Unit of measurement for weight/volume/count', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Numeric amount; meaning depends on unit_type (e.g. 500 mL, 1 kg, 100 g)', max_digits=10),
        ),
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Why do you need this category?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Admin feedback to seller')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
