# Generated by Django 6.0 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_unit_type_alter_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Optional feedback shown to the seller on rejection.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin must approve before the product is visible to buyers.', max_length=15),
        ),
    ]
