# Generated by Django 6.0 on 2026-07-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_admin_note_product_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price. If set, this price will be used instead of the normal price.', max_digits=10, null=True),
        ),
    ]
